version: '3' 

services:
 redis:
  image: redis
  ports:
   - 6379:6379
  volumes:
   - /home/osku/Documents/docker18_materials/redis/data:/data

 backend:
  image: jojokine/backend
  build: /home/osku/Documents/docker18_materials/backend-example-docker-master
  environment:
   - REDIS=redis
  volumes:
   - /home/osku/Documents/docker18_materials/backend-example-docker-master/logs.txt:/logs.txt
  ports:
   - 8000:8000
 
 frontend:
  image: jojokine/frontend
  build: /home/osku/Documents/docker18_materials/frontend-example-docker-master
  ports:
   - 5000:5000
