version: '3' 

services:
 postgres:
  image: postgres
  ports:
   - 5432:5432
  environment:
   - POSTGRES_PASSWORD=mysecretpassword
  volumes:
   - /home/osku/Documents/docker18_materials/psql/data:/var/lib/postgresql/data

 redis:
  image: redis
  ports:
   - 6379:6379
  volumes:
   - /home/osku/Documents/docker18_materials/redis/data:/data

 backend:
  image: jojokine/backend
  build: /home/osku/Documents/docker18_materials/backend-example-docker-master
  environment:
   - FRONT_URL=http://localhost:5000
   - REDIS=redis
   - DB_USERNAME=postgres
   - DB_PASSWORD=mysecretpassword
   - DB_HOST=postgres
  volumes:
   - /home/osku/Documents/docker18_materials/backend-example-docker-master/logs.txt:/logs.txt
  ports:
   - 8000:8000
 
 frontend:
  image: jojokine/frontend
  build: /home/osku/Documents/docker18_materials/frontend-example-docker-master
  environment:
   - API_URL=http://localhost/api
  ports:
   - 5000:5000

 nginx:
  image: nginx
  ports:
   - 80:80
  volumes:
   - /home/osku/Documents/docker18_materials/nginx/nginx.conf:/etc/nginx/nginx.conf
